namespace Aeroverra.Lib.Queues
{
    /// <summary>
    /// Standard wrapper for messages flowing through the queue. Carries a typed business
    /// payload plus the metadata the framework needs (id for correlation, attempt counter
    /// for capped app-managed retries, publish time for SLA tracking).
    ///
    /// Producers wrap via <c>IQueuePublisher.PublishAsync&lt;T&gt;(...)</c>; consumers receive
    /// the deserialized envelope by extending <c>QueueMessageHandler&lt;T&gt;</c>. Use the raw
    /// escape hatches — <c>IQueuePublisher.PublishRawAsync</c> and the bare
    /// <c>IQueueMessageHandler</c> interface — when the envelope shape isn't desired.
    /// </summary>
    public sealed record Envelope<T>
    {
        /// <summary>
        /// Stable id for the logical message. Generated by the publisher when not supplied;
        /// preserved across republishes so attempts of the same message share a correlation id.
        /// </summary>
        public string Id { get; init; } = null!;

        /// <summary>
        /// Zero on first delivery, incremented each time the typed handler base republishes
        /// after a <c>QueueHandlerResult.Retry(...)</c> outcome.
        /// </summary>
        public int AttemptCount { get; init; }

        /// <summary>
        /// Time the original message was first published. Preserved across republishes so
        /// SLA / age-based monitoring remains accurate even after retries.
        /// </summary>
        public DateTimeOffset TimePublished { get; init; } = DateTimeOffset.UtcNow;

        /// <summary>
        /// The typed business payload — whatever shape the producer/consumer agreed on.
        /// </summary>
        public T Payload { get; init; } = default!;
    }
}
